name: Changesets
on:
  push:
    branches:
      - release
    paths-ignore:
      - "docs/**"
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Setup npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          echo "git-checks=false" >> .npmrc

      - run: pnpm install

      - name: create and publish versions
        uses: changesets/action@v1.4.6
        id: changesets
        with:
          publish: pnpm ci:publish
          version: pnpm ci:version
          commit: "ci: changesets versions"
          title: "ci: changesets versions"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish dist
        if: steps.changesets.outputs.published == 'true'
        run: pnpm run ci:pub:dist
